### ISSUE TITLE
Can we update to bring in the awesome changes to react-templates?

### ISSUE THREAD

**Issue by steezeburger** [wix/grunt-react-templates#4]
Namely working with React ^15.0.0 and the awesome rt-import syntax. I've been running a fork of this and doing it manually, but I think I'm doing something wrong this time around and simply changing the version number and reinstalling didn't help.

Edit: Let me be a little more candid. I'm getting an error when trying to bundle (browserify) that 'react/addons' cannot be found. I thought updating to React 15 and react-templates 0.5.2 would remedy this. Any ideas?

Edit2: I think this is actually because I'm not setting the target version, but simply adding a targetVersion key to the options object doesn't seem to be working.

```
        reactTemplates: {
            checkin: {
                src: ['js/src/react-apps/checkin-react/**/*.rt'],
                options: {
                    modules: 'commonjs',
                    format: 'stylish'
                }
            },
            checkinLite: {
                src: ['js/src/react-apps/checkinLite-react/**/*.rt'],
                options: {
                    modules: 'commonjs',
                    format: 'stylish'
                }
            },
            widget: {
                src: ['js/src/react-apps/widget-react/**/*.rt'],
                options: {
                    targetVersion: '15.0.0',
                    modules: 'commonjs',
                    format: 'stylish'
                }
            }
        }
```

Edit3: I wasn't seeing the check for targetVersion in the dist code, so I re-ran the prepublish and lint scripts. I'm seeing the updated check for targetVersion in dist/ now, but it is still returning 'react/addons' when a targetVersion of 15.0.1 is specified. I think that's as far as I'll be able to get. Not sure where to go from here.

Edit4: Ha, okay so I aliased react:react/addons in my browserify options, and I got it working, but I feel like this is a hack. Shouldn't I just be getting 'react' instead of 'react/addons'?

**Comment by idok** [comment]
released 0.6.0
